In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("C:\\Users\\mailt\\Desktop\\Diya\\Projects\\ETL\\transactions_input.csv")

In [24]:
data

     transaction_id customer_id  amount currency transaction_date product_id
0              t001     cust001  120.50      USD       20/09/2025       p100
1              t002     cust002   85.00      USD       20/09/2025       p200
2              t003     cust001   20.00      USD       20/09/2025       p100
3              t004     cust003   45.00      USD       21/09/2025       p300
4              t005     cust004  300.00      USD       21/09/2025       p400
...             ...         ...     ...      ...              ...        ...
7495            nan     cust108  443.95      USD       29/08/2025       p700
7496          t7497     cust449  352.93      USD       10/08/2025       p268
7497          t7498     cust206  335.63      USD       18/08/2025       p893
7498          t7499     cust151  126.55      USD       03/09/2025       p231
7499          t7500     cust116  315.25      USD       07/09/2025       p730

[7500 rows x 6 columns]

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    7500 non-null   object
 1   customer_id       7500 non-null   object
 2   amount            7500 non-null   float64
 3   currency          7500 non-null   object
 4   transaction_date  7500 non-null   object
 5   product_id        7500 non-null   object
dtypes: float64(1), object(5)
memory usage: 351.7+ KB

In [26]:
data["transaction_id"] = data["transaction_id"].str.strip()

In [27]:
cleaned_data = data[data["transaction_id"].notna() & (data["transaction_id"] != "") & (data["transaction_id"] != "nan")]
cleaned_data

     transaction_id customer_id  amount currency transaction_date product_id
0              t001     cust001  120.50      USD       20/09/2025       p100
1              t002     cust002   85.00      USD       20/09/2025       p200
2              t003     cust001   20.00      USD       20/09/2025       p100
3              t004     cust003   45.00      USD       21/09/2025       p300
4              t005     cust004  300.00      USD       21/09/2025       p400
...             ...         ...     ...      ...              ...        ...
7494          t7495     cust443  390.82      USD       10/09/2025       p390
7496          t7497     cust449  352.93      USD       10/08/2025       p268
7497          t7498     cust206  335.63      USD       18/08/2025       p893
7498          t7499     cust151  126.55      USD       03/09/2025       p231
7499          t7500     cust116  315.25      USD       07/09/2025       p730

[6500 rows x 6 columns]

In [28]:
empty_data = data[data["transaction_id"].isna() | (data["transaction_id"] == "") | (data["transaction_id"] == "nan")]
empty_data

     transaction_id customer_id   amount currency transaction_date product_id
16              nan     cust054   440.52      USD       04/08/2025       p611
20              nan     cust046    76.61      USD       19/08/2025       p852
37              nan     cust347   329.29      USD       16/08/2025       p378
42              nan     cust047    91.35      USD       02/08/2025       p535
57              nan     cust321   399.90      USD       20/09/2025       p143
...             ...         ...      ...      ...              ...        ...
7480            nan     cust053   185.73      USD       08/08/2025       p102
7485            nan     cust025  1210.49      USD       17/08/2025       p297
7487            nan     cust265   159.11      USD       15/09/2025       p533
7492            nan     cust355    49.88      USD       15/08/2025       p490
7495            nan     cust108   443.95      USD       29/08/2025       p700

[1000 rows x 6 columns]

In [29]:
cleaned_data.to_csv("transactions_cleaned.csv", index=False)
empty_data.to_csv("transactions_empty.csv", index=False)